version: '3.4'
services:

  vpn:
    container_name: vpn
    image: dperson/openvpn-client:armhf
    cap_add:
      - net_admin # required to modify network interfaces
    restart: unless-stopped
    volumes:
      - /dev/net/tun:/dev/net/tun # tun device
      - ${HOME}/.vpn:/vpn # OpenVPN configuration
    ports:
      - 8112:8112 # port for deluge web UI to be reachable from local network
    command: '-d -r 10.1.10.0/24' # route local network traffic

  deluge:
    container_name: deluge
    depends_on:
      - vpn
    image: lsioarmhf/deluge:latest
    restart: always
    network_mode: service:vpn # run on the vpn network
    environment:
      - PUID=1000 # default user id, for downloaded files access rights
      - PGID=1000 # default group id, for downloaded files access rights
      - TZ=Europe/Paris # timezone
    volumes:
      - ${HOME}/downloads/ongoing:/downloads # download folder
      - ${HOME}/.config/deluge:/config # config files

  jackett:
    container_name: jackett
    image: lsioarmhf/jackett:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000 # default user id, for downloaded files access rights
      - PGID=1000 # default group id, for downloaded files access rights
      - TZ=Europe/Paris # timezone
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${HOME}/downloads/ongoing/torrent-blackhole:/downloads # place where to put .torrent files
      - ${HOME}/.config/jackett:/config # config files

  hydra:
    container_name: hydra
    image: lsioarmhf/hydra2:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000 # default user id, for downloaded files access rights
      - PGID=1000 # default group id, for downloaded files access rights
      - TZ=Europe/Paris # timezone
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${HOME}/downloads/ongoing/nzb-blackhole:/downloads # place where to put .torrent files
      - ${HOME}/.config/hydra:/config # config files

  nzbget:
    container_name: nzbget
    image: lsioarmhf/nzbget:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000 # default user id, for downloaded files access rights
      - PGID=1000 # default group id, for downloaded files access rights
      - TZ=Europe/Paris # timezone
    volumes:
      - ${HOME}/downloads/ongoing:/downloads/incomplete # download folder
      - ${HOME}/downloads:/downloads/completed # download folder
      - ${HOME}/downloads/ongoing/nzb-blackhole:/downloads/nzb # place where to put .torrent files
      - ${HOME}/.config/nzbget:/config # config files

  sonarr:
    container_name: sonarr
    image: lsioarmhf/sonarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000 # default user id, for downloaded files access rights
      - PGID=1000 # default group id, for downloaded files access rights
      - TZ=Europe/Paris # timezone
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${HOME}/.config/sonarr:/config # config files
      - ${HOME}/downloads/series:/tv # tv shows folder
      - ${HOME}/downloads/ongoing:/downloads # download folder

  radarr:
    container_name: radarr
    image: lsioarmhf/radarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000 # default user id, for downloaded files access rights
      - PGID=1000 # default group id, for downloaded files access rights
      - TZ=Europe/Paris # timezone
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${HOME}/.config/radarr:/config # config files
      - ${HOME}/downloads/movies:/movies # movies folder
      - ${HOME}/downloads/ongoing:/downloads # download folder

  organizr:
    container_name: organizr 
    image: lsioarmhf/organizr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000 # default user id, for downloaded files access rights
      - PGID=1000 # default group id, for downloaded files access rights
    volumes:
      - ${HOME}/.config/organizr:/config # config files

  plex-server:
    container_name: plex-server
    image: lsioarmhf/plex:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris # timezone
    network_mode: host
    volumes:
      - ${HOME}/.plex/db:/config # plex database
      - ${HOME}/.plex/transcode:/transcode # temp transcoded files
      - ${HOME}/downloads:/data # media library
